name: "Binance Spot Signals (WebSocket)"
version: "1.5.0"
slug: "binance_spot_signals_ws"
description: "Async Binance WebSocket signals bot (1h/15m/5m) with Telegram alerts. Raspberry Pi 5 ready."
arch:
  - aarch64
  - armv7
  - amd64
stage: experimental
startup: services
init: false
boot: auto
map:
  - addon_config:rw
  - share:rw
options:
  symbols: ["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT"]
  timezone: "Asia/Seoul"
  vwap_session_reset: "00:00"
  cooldown_minutes_per_symbol: 10
  send_startup_message: true
  min_alert_level_n: 4
  ws_url: "wss://stream.binance.com:9443"
  rest_base: "https://api.binance.com"
  history_bars: 300
  log_level: "INFO"
  tg_token: ""
  tg_chat_id: ""
  ema_fast_1h: 20
  ema_slow_1h: 50
  ema_200_15m: 200
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  rsi_period: 14
  rsi_zone_low: 40
  rsi_zone_mid: 50
  rsi_zone_high: 60
  atr_period: 14
  atr_sl_mult: 1.3
  vol_sma_period: 20
  vol_spike_mult: 1.5
  supertrend_enabled: false
  supertrend_period: 10
  supertrend_multiplier: 3.0
schema:
  symbols:
    - str
  timezone: str
  vwap_session_reset: str
  cooldown_minutes_per_symbol: int
  send_startup_message: bool
  min_alert_level_n: int
  ws_url: str
  rest_base: str
  history_bars: int
  log_level: str
  tg_token: password
  tg_chat_id: str
  ema_fast_1h: int
  ema_slow_1h: int
  ema_200_15m: int
  macd_fast: int
  macd_slow: int
  macd_signal: int
  rsi_period: int
  rsi_zone_low: int
  rsi_zone_mid: int
  rsi_zone_high: int
  atr_period: int
  atr_sl_mult: float
  vol_sma_period: int
  vol_spike_mult: float
  supertrend_enabled: bool
  supertrend_period: int
  supertrend_multiplier: float
